### ISSUE TITLE
Setting custom Ids which can be used for searching etc

### ISSUE THREAD

**Issue by elfisko** [CargoChain/doc#1]
Currently, Cargo chain supports search using the ID, or the Alias.
Since the Alias isn't shared, it needs to be set every time the profile transitions between organisations.
It would be great to be able to have a custom ID that could be set by the creator of the profile, in addition to the Alias and private Id

**Comment by brezho** [comment]
So far we have no intention to provide the ability to expose any user-defined public id. These would be more often than not 'human-friendly' or sequential ids and as such they would be subject to fishing.
At the moment the easiest would be that the creator of the profile publishes an event with public or downstream visibility which contain the custom ID so you can read it down the stream.

**Comment by elfisko** [comment]
Thank you for your quick response, 
Following up on your suggestion of using an event, can I get events belonging to a profile from cargo chain which are only a certain type? i.e. {profileId}/events?type=OrgId => returns that profiles OrgId event(s)

**Comment by brezho** [comment]
CargoChain logic is based around client handling events as they happen (by opposition to clients sending ad-hoc queries on a regular basis). 
So you can register a hook on the profile (see "Register Profile Hook") and you can get notified whenever an event of type 'OrgId' is happening on a profile.
