### ISSUE TITLE
delete organisation hook not working

### ISSUE THREAD

**Issue by harrisonJlg** [CargoChain/doc#2]
![image](https://user-images.githubusercontent.com/37578073/64932012-23431580-d890-11e9-97fd-23f1f674b056.png)

![image](https://user-images.githubusercontent.com/37578073/64932023-3e158a00-d890-11e9-9c08-1637b56fedde.png)

**Comment by dbaertschiger** [comment]
Error in the documentation: the parameter has to be specified as a query parameter and not in body of the request.
`POST /deleteOrganisationHook?id={hookId}`

The documentation has been updated.
