### ISSUE TITLE
Issue uploading files - event with multiple files

### ISSUE THREAD

**Issue by harrisonJlg** [CargoChain/doc#4]
**Issue:** 

In an event with multiple files (tested up to 3 files), only the final file in the array will upload a file correctly.

**Error**

`[Error] [/upload?id=CF-6ZM44-4Q6LV] [046.56ms] missing or invalid parameter: id
Type: X.Web2.HttpException
Message: missing or invalid parameter: id
Source: Api2
StatusCode : BadRequest
Data : System.Collections.ListDictionaryInternal
TargetSite : Void <ConfigureProfileHandlers>b__20_5(Api2.ProfileContext)
HResult : -2146233088
Stack trace: :    at Api2.Api2.<ConfigureProfileHandlers>b__20_5(ProfileContext ctx) in C:\projects\ccv4\LaMallette\api2.cargochain.com\Api2.Profile.Configure.cs:line 170
   at Api2.Api2.<>c__DisplayClass79_0.<HandleProfileCall>b__0(ProfileContext ctx) in C:\projects\ccv4\LaMallette\api2.cargochain.com\Api2._main.cs:line 107`

![image](https://user-images.githubusercontent.com/37578073/69511403-d2911c80-0fa4-11ea-8a7f-bafc8a163b3d.png)

![image](https://user-images.githubusercontent.com/37578073/69511197-2c451700-0fa4-11ea-8695-63bdf3e71579.png)

**Comment by dbaertschiger** [comment]
Fixed in version 2.0.0.37
