### ISSUE TITLE
test server - Portal SDK error

### ISSUE THREAD

**Issue by harrisonJlg** [CargoChain/doc#6]
It looks like the SDK is minified and served correctly, works in dev as well.

![image](https://user-images.githubusercontent.com/37578073/72378712-cf313a80-3776-11ea-9cd6-6f1d287c122c.png)

**Comment by dbaertschiger** [comment]
Fix in version 2.0.0.45.
Minification has been disabled in production for sdk.ui.min.js (issue with terser-webpack-plugin).

**Comment by dbaertschiger** [comment]
If the user doesn't have authorization and try to access https://portal-tests.cargochain.com, the redirection is not correctly handled. So if necessary, access to https://portal-tests.cargochain.com/login
